[build]
builder = "nixpacks"
buildCommand = "npm ci && npx drizzle-kit push"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[service]
internalPort = 3000
